apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-app
  template: 
    metadata:
      name: https-pod
      labels:
        app: httpd-app
    spec:     
      containers:
      - name: httpd-container
        image: iamdevopstrainer/httpd:v1
        ports:
        - containerPort: 80
